# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane



default_platform(:ios)

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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" # Webhook URL created in Slack
    increment_build_number({
      build_number: latest_testflight_build_number + 0.1
    })
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile
    build_app(scheme: "LearnCombine")
    upload_to_testflight
    slack(message: "Successfully distributed a new beta build")
  end
end
